apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-volume-2
  labels:
    type: local
spec:
  storageClassName: logging
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/logging/2"
